const AccessControl = require('accesscontrol')
const ac = new AccessControl()

ac.grant('user')
	.readOwn('favorites')
	.readOwn('listing')
	.readOwn('profile')
	.readAny('category')
	.readAny('favorites')
	.readAny('listing')
	.readAny('profile')
	.updateOwn('listing')
	.updateOwn('profile')
	.deleteOwn('favorites')
	.deleteOwn('listing')

ac.grant('admin')
	.extend('user')
	.createAny('category')
	.readAny('profiles')
	.updateAny('category')
	.updateAny('listing')
	.updateAny('profile')
	.deleteAny('category')
	.deleteAny('favorites')
	.deleteAny('listing')
	.deleteAny('profile')

module.exports = ac
